version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=postgres://postgres:REPLACE_ME_WITH_A_PASSWORD@db:5432/postgres
      - NEXTAUTH_SECRET="REPLACE_ME_WITH_A_RANDOM_STRING"
      - NEXTAUTH_URL="http://localhost:3000"
      - DISCORD_CLIENT_ID=""
      - DISCORD_CLIENT_SECRET=""

  db:
    platform: "linux/amd64"
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=REPLACE_ME_WITH_A_PASSWORD
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: